### ISSUE TITLE
How to call 'remove_noise()' when training?

### ISSUE THREAD

**Issue by forhonourlx** [OctThe16th/Noisy-A3C-Keras#1]
Hi OctThe16th,

What's the proper way to call 'remove_noise()' when training in keras?
Could you kindly show some code?
Thanks for your help.

**Comment by LuEE-C** [comment]
remove_noise() should be called after training, when the exploration is over, to make the layer deterministic.

Something like that should do the trick self.model.get_layer('out_actions').remove_noise()

**Comment by forhonourlx** [comment]
`	def reset_all_noisy_denses(self, model, keyword='noisy'):
		layer_name_list = [layer.name for layer in model.layers if keyword in layer.name]
		print('layer_name_list:',layer_name_list)
		for l_ in layer_name_list:
			model.get_layer(l_).remove_noise()`

Many thanks. It does work.
